[build]
    command = "make clean"

[[redirects]]
    from = "/404.html"
    to = "/page/404/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/blog"
    to = "/page/blog/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "/page/404/index.html"
    status = 404
    force = false
