[[redirects]]
    from = "/*"
    to = "/page/404/index.html"
    status = 404
    force = false

[[redirects]]
    from = "/404.html"
    to = "/page/404/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/game"
    to = "//www.youtube.com/watch?v=dQw4w9WgXcQ"
    status = 301
    force = true

